### ISSUE TITLE
Problem with PDP

### ISSUE THREAD

**Issue by lpkoh** [rallyhealth/pytalite#2]
Hi, I installed your requirements, and all my plots work up till calling:
from pytalite.interpretation import partial_dependence_plot
partial_dependence_plot(df_test, 'Survived', model, 'Sex_female', predictor=lambda x: model.predict_proba(x)[:, 1], columns_to_exclude=(), n_jobs=-1)

Then, it stops working, with the following error message:
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\lpkoh\Anaconda3\envs\pytaliteEnv\lib\site-packages\multiprocess\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\lpkoh\Anaconda3\envs\pytaliteEnv\lib\site-packages\multiprocess\pool.py", line 44, in mapstar
    return list(map(*args))
  File "..\pytalite\interpretation.py", line 703, in _comp_pd_with_value
    return predictor(X_copy).mean()
  File "<ipython-input-29-888b6313befa>", line 1, in <lambda>
NameError: name 'model' is not defined
"""

The above exception was the direct cause of the following exception:

NameError                                 Traceback (most recent call last)
<ipython-input-29-888b6313befa> in <module>
      1 partial_dependence_plot(df_test, 'Survived', model, 'Sex_female', predictor=lambda x: model.predict_proba(x)[:, 1],
----> 2                         columns_to_exclude=(), n_jobs=-1)

~\Desktop\Basis\Repos\pytalite-master\pytalite\interpretation.py in partial_dependence_plot(df, y_column, model, feature_column, predictor, columns_to_exclude, n_jobs)
    854 
    855         if _feature_type(feature_values) == "categorical":
--> 856             return _partial_dependence_plot_cat(X, predictor, feature_idx, y_column, feature_column, n_jobs)
    857         else:
    858             return _partial_dependence_plot_num(X, predictor, feature_idx, y_column, feature_column, n_jobs)

~\Desktop\Basis\Repos\pytalite-master\pytalite\interpretation.py in _partial_dependence_plot_cat(X, predictor, features, y_name, feature_name, n_jobs, one_hot)
    743         xticklabels = list(map(lambda x: "Cat. %d" % int(x), vals))
    744 
--> 745     stats = _partial_dependence(vals, X, predictor, features, n_jobs)
    746 
    747     indices = np.arange(len(vals))

~\Desktop\Basis\Repos\pytalite-master\pytalite\interpretation.py in _partial_dependence(vals, X, predictor, feature, n_jobs)
    725             stats = []
    726             sys.stderr.write("Start Multiprocessing, num_processes=%d" % len(executor_instance._pool))
--> 727             for stat in executor_instance.map(partial_dependence_func, vals, chunksize):
    728                 stats.append(stat)
    729 

~\Anaconda3\envs\pytaliteEnv\lib\site-packages\multiprocess\pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

~\Anaconda3\envs\pytaliteEnv\lib\site-packages\multiprocess\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

NameError: name 'model' is not defined

**Comment by lpkoh** [comment]
It appears that changing n_jobs = 1 solves this problem. Why is this so?

**Comment by victorconan** [comment]
Hi, thanks for your interest in pytalite.

From the error, it seems your first run is missing `model`. You need to pass a model object into the function. 

Best
