### ISSUE TITLE
Do you assume lack of correlation for partial dependence?

### ISSUE THREAD

**Issue by lpkoh** [rallyhealth/pytalite#3]
Was wondering how you compute the partial dependence.

**Comment by victorconan** [comment]
Hi Ipkoh,

We computed the partial dependence following the algorithm in [Friedman, Jerome H. “Greedy function approximation: A gradient boosting machine.” Annals of statistics (2001): 1189-1232.](https://projecteuclid.org/euclid.aos/1013203451)

You can see the code implementation in our repo.

Best

**Comment by victorconan** [comment]
> Hi Ipkoh,
> 
> We computed the partial dependence following the algorithm in [Friedman, Jerome H. “Greedy function approximation: A gradient boosting machine.” Annals of statistics (2001): 1189-1232.](https://projecteuclid.org/euclid.aos/1013203451)
> 
> You can see the code implementation in our repo.
> 
> Best
